### ISSUE TITLE
formatstring with an image without absolute/relative path, exception by subprocess: file not found.

### ISSUE THREAD

**Issue by peppelinux** [archeos/ppt-archeos#8]
/usr/local/bin
Working directory created: /tmp/osm-bundler-Y8SRl7
BundlerMatching executable path: KeyMatchFull
Sift executable path: sift
Entry for the camera 'HUAWEI', 'HUAWEI Y530-U00' does not exist in the camera database
Can't estimate focal length in pixels for the photo '/home/ulisse/Scrivania/gufino/IMG_20150403_183123.jpg'
Copy of the photo has been scaled down to 1200x900
IMG_20150403_183123
Extracting features with the SIFT method from VLFeat library...
Traceback (most recent call last):
File "/usr/local/bin/RunBundler", line 17, in 
main()
File "/usr/local/bin/RunBundler", line 11, in main
manager.preparePhotos()
File "/usr/local/lib/python2.7/dist-packages/osmbundler/**init**.py", line 162, in preparePhotos
self._preparePhoto(photoInfo)
File "/usr/local/lib/python2.7/dist-packages/osmbundler/__init__.py", line 275, in _preparePhoto
self.extractFeatures(photo)
File "/usr/local/lib/python2.7/dist-packages/osmbundler/__init__.py", line 342, in extractFeatures
self.featureExtractor.extract(photo, self.photoDict[photo])
File "/usr/local/lib/python2.7/dist-packages/osmbundler/features/siftvlfeat.py", line 19, in extract
vlfeatTextFile = open("%s.key" % photo, "r")
IOError: [Errno 2] No such file or directory: 'IMG_20150403_183123.key'

**Comment by escnqh** [comment]
Have you solved this problem?@peppelinux
